port: 8081
core:
  user:
    userStoreConf:
        url: localhost:27017
        username: root
        password: password
        database: blab
        collection: user
  oauth:
    tokenStoreConf:
        url: localhost:6379