port: 8081
mongoConf:
  url: localhost:27018
  username: root
  password: password
  database: blab
userCollection: user
core:
  user:
    userStoreConf:
        url: localhost:27017
        username: root
        password: password
        database: blab
        collection: user